ddddkOkx;'lxc'........,lodooool:'.',::;clooooooooooooooooooooooooooooooooooooooooooooooooooooooooddd
dddxOOkxc;oxl'........;odoooooool:'',;;;:clooooooooooooooooooooooooooooooooooooooooooooooddddddddddd
dddxkkkxoldxl'........;odooddooodol;',,',;::looooooooooooooooooooooooooooooooooooooddddddddddddddddd
xddxxkkkxkkkl'........;oddddddddoodoc,''',,,,:looooooooooooooooooooooooooddddddddddddddddddddddddddd
xxxxkkkkkOOkc.........,ldddddddddddddc,''''..',;coooooddddoodddddolloooooooddddddddddddddddddddddddd
xxkkOOOOOkOk:.........'lddddddddddddddc,','....',:ccloddddddddddddoodddddoooddddddddddddddddddxxxxxx
xxkO000OOkOk:.........,oxddddddddddddddl:;'.....',;;;clodddddddddddodddddddodddddddddxxxxxxxxxxxxxkO
xxkOK00OOOkd;.........;oxddddddddddddddxdl;..'...',,,;::codxdddddddddddxdxxoodxxxxxxxxxxxxxxxxxxxxxx
kxxOK00000Od,.........;oxxxxxdxxddxxddxxkxc'.,'..,cll:,,;;cldxxxxdxxxxxxxxxoldxxxxxxxxxxxxxxxxxxxxxx
kxx0K00O00Oo,.'.......;dxxxxxxxxxxxxxxxkkkd;:d:..':oxdl;',,',cdxkO0KKOOOkxxdldxxxxxxxxxxxxxxxxxkkkkk
kxxO0OkOOOko'.'''''...;dkxxxxxxxxxxxxxxkkkxlok:..,;oxxxo,','.';lkXWWNXK00kkxodkxxxxkxxxxkxkkkkkkkkkx
kxxk0OOOOOxl'.'''.'''.:xkxxxxxxxxxxxxxkkkkkxxOo'.',lkxxxo;''..',;lOXXK0Okkkxodkkxxdxxddxkkkkkkkkxkxd
kxxO0K0O0Oxc...''..''.:xkkkkkkkkkkkkkkkkxxxkOOo'...:xkkkkdc'..,c;',cdkOOkkkkookxxxkkkdoxkkkkkOkollxk
kkO0000OOkxc.'....''..ckkkkkkkkkkkkkkkkkkkkkOOo'...:xOkkOkd:,,'ld:''':oxkkkOdlddxkkkkxoxOOOOOOxokkoo
OkO00OOOOOkc....'..'..ckOkkkkkkkkkkkkkkkkkkkO0o,...:xOkkO0kodo':kd:'.',:lxO0xokkxOOkkkkkOOOOOOOxdodk
OkO000OOOOx:...''..'..lOOOOOOOOOOOOOOOkkxkkkOOd,...;xOOO00Okkx,;xOx:.',,',lOkdk0OOOOkkOOOOOOOOO0kdkO
OO0000OOOOx:...''''..'oOOOOOOOOOOOOOOOOkOOOkOOd,...;x0OOO0OOOk;'dOOdc;:l;.',:lOKXK00kxO0000000O0Odk0
OO000OO00Ox;.''..'...,oOOOOOOOOO0000KK0kO0OO0Od,...;k0OOOO000O:'oOOOkl:xo;;;'';oO000OkO0OOO0XXKK0dol
00000O000Oo,.'...'...'d0O00O0000000000OkkOOkkOd,...;k000O0K0KOc'lOOOOo:dOxoll;'';lx00kk00OkOKKKKKdc;
0000000000d,..''''''.'dOOKKK0KKK0KK00K0OOOkkkOx;...;k000O0000Oc.cOOkkd:d0OoxOlcl;,,cdookOOOkkO0XNO:'
OO0000000Oo,.','''''''coodxxoooolllcoxkkOkkkkOx;...,d0KK0kOOOOl'cOkkkd:o0Odx0ooxdoc::;ckOO0Odd0NNd;'
xO0OO00000d'.''''''''..',;::;:lllc;;;,:dkkxxxkx;....;cloxkOOOOo',dkkkx:o0OoxKoldddxxxoccclollldkd:;,
dk000000OOo''''''''.'..'',;:,,cool:coooxkxxkkkx;...'loccdO0000d',dOOOk:l0Olo0dcddxxxkxooodo:cool;;:;
xkOO0000kkl'...'''....,:'.':,.',,;;cOXKOkxxxxkx:...'oxllxOOO00d,.lkkOkcl00olOo:odddoooccloocoxxl:::,
xkkkOOOOkkl...''......,;,,;:;,:lloookOOkkkkkOOkc'...,:::cloodxo,'cddxkolxxl:l:,:c::;;,'',;coxO0Okxo:
kkkO000Okko,''',''''',:c:;,''''',,;,;;;::cccccc:,'',,''',,,,;;;;;;:::llcccccc;',;;;;:clodkOOOO00Okkk
lllllllcc:;;,,,,',,,,,,,,,,,,,,,,,,;;,;;;;;;;;;::::::::::::::::::;;::::::::::;;:looxkOOOOOOO0000xodd
'''''''''',,,,,,,,,,,;;;;;;::::::;;;;;;;;;;;;;;,,,,,,,,,,,'''',,,,,,,,,,,,;cldxkOOOOOO0OO00000K0xok0
''''''''''''.''''.''''',,,,,;;;;;;:::::ccccllllloooooolc:;;;;;;;;,,,,,,;:ldxxxxxxxxxxxxxddxxxxxxx0XK
;;:::::::ccccccclllllooooooddddddddxxxxxxxxxddoollccc:;;,,,,,,,'''',,,,;;;;;;,;;;;;;;;;;,;;;;;;;o0XX
ooooooooooodddddddddddddddddxxxxddddoooollcc::;;,,,,,,,,,,,'',;:clodddddddddxxxxxxxxxxkkkkkkkOOO0XNN
ddddddddddddddxxxxxxxddoolllccccccc::;;;;;,,,,,,,,,,''''',;:codxkkOOOOOOOOOOOOOOOOOOOOOOO00000KKKXNN
dddddddddddoollcc::;;;;;,;;;;;;;;;,,,,,,,,'','''''''',,:codxkkOOOOOOOOOOOOOOOOOOOOOOOOOO00000KKK00KX
ddddollc:;,,'....'',;;:::::;,,,,,,,,''',''''''''''',;codxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000KK0Okdox0
